trueque_tools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("tt_app.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tt_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name="home"),
    path("registro/", views.registro, name="registro"),
    path("ingreso/", views.ingreso, name="ingreso"),
    path("logout/", views.cerrar_sesion, name="logout"),
    path("crear_producto/", views.crear_producto, name="crear_producto"),
    path("productos/", views.productos, name="productos"),
    path("buscar_productos/", views.buscar_productos, name="buscar_productos"),
    path("productos/id/<int:id>", views.detalle_producto, name="detalle_producto"),
]

tt_app/models.py
from django.db import models
from django.db.models.fields.files import ImageField
from django.db.models.query import QuerySet
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager


# Create your models here.
# Creating users and superusers
class MyCustomUserManager(BaseUserManager):
    def create_user(
        self, email, first_name, last_name, dni, phone, birthdate, password=None
    ):
        if not email:
            raise ValueError("El nombre de usuario debe ser tu correo electrónico.")
        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            dni=dni,
            phone=phone,
            birthdate=birthdate,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        user = self.create_user(
            email=self.normalize_email(email),
            first_name="",
            last_name="",
            dni="",
            phone="",
            birthdate="1900-01-01",
            password=password,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


# User model
class CustomUser(AbstractBaseUser):
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, blank=True)
    first_name = models.CharField(
        max_length=50,
        blank=True,
    )
    last_name = models.CharField(
        max_length=50,
        blank=True,
    )
    date_joined = models.DateTimeField(
        verbose_name="date joined",
        auto_now_add=True,
    )
    last_login = models.DateTimeField(verbose_name="last login", auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    dni = models.CharField(max_length=10, blank=True, null=True)
    phone = models.CharField(max_length=30, blank=True, null=True)
    birthdate = models.DateField(
        default="1990-01-01",
        blank=True,
    )
    hide_email = models.BooleanField(default=True)

    objects = MyCustomUserManager()

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name", "birthdate"]

    def __str__(self):
        return self.username

    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True


# Product model
class Producto(models.Model):

    nombre = models.CharField(max_length=50)
    descripcion = models.TextField(
        validators=[
            MinLengthValidator(10, "Este campo debe contener al menos 10 caracteres")
        ],
        max_length=550,
    )

    class Categoria(models.IntegerChoices):
        categoria_1 = 1, _("$0-$4999")
        categoria_2 = 2, _("$5000-$9999")
        categoria_3 = 3, _("$10000+")

    categoria = models.IntegerField(choices=Categoria.choices)
    fecha_de_publicacion = models.DateTimeField(auto_now=True)

    imagen = ImageField(blank=True, upload_to="media/")
    promocionado = models.BooleanField(default=False)
    activo = models.BooleanField(default=True)
    usuario = models.ForeignKey(
        CustomUser, on_delete=models.CASCADE, related_name="productos"
    )

    def __str__(self):
        return self.nombre + "\t(" + str(self.usuario.id) + ")"

tt_app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from .models import CustomUser, Producto
from django.core.exceptions import ValidationError
import datetime


def validate_age(value):
    birthdate = value
    day = int(birthdate.strftime("%d"))
    month = int(birthdate.strftime("%m"))
    year = int(birthdate.strftime("%Y"))
    today = datetime.date.today()
    age = today.year - year - ((today.month, today.day) < (month, day))
    if age < 18:
        raise ValidationError("Tenés que ser mayor de edad para registrarte.")


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(
        max_length=255, help_text="Ingresá tu dirección de correo."
    )
    first_name = forms.CharField(
        max_length=60,
        error_messages={"required": "Ingresá tu nombre"},
    )
    last_name = forms.CharField(
        max_length=60,
        error_messages={"required": "Ingresá tu apellido"},
    )
    dni = forms.CharField(
        max_length=20,
    )
    phone = forms.CharField(
        max_length=30,
    )
    birthdate = forms.DateField(
        validators=[validate_age],
        error_messages={
            "required": "Necesitamos tu fecha de nacimiento. Tenés que ser mayor de edad para registrarte."
        },
    )

    class Meta:
        model = CustomUser
        fields = (
            "email",
            "password1",
            "password2",
            "first_name",
            "last_name",
            "dni",
            "phone",
            "birthdate",
        )

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        self.fields["dni"].required = False
        self.fields["phone"].required = False

    def clean_email(self):
        email = self.cleaned_data["email"].lower()
        try:
            user = CustomUser.objects.get(email=email)
        except Exception as e:
            return email
        raise forms.ValidationError(f"El email {email} ya posee una cuenta.")


class CreacionDeProducto(forms.ModelForm):
    class Meta:
        model = Producto
        fields = ["nombre", "descripcion", "categoria", "imagen"]

    nombre = forms.CharField(
        label="Nombre del producto",
        max_length=50,
        widget=forms.TextInput(attrs={"class": "input mb-2", "style": "width: 100%;"}),
    )
    descripcion = forms.CharField(
        label="Descripción",
        max_length=200,
        min_length=10,
        widget=forms.Textarea(attrs={"class": "input mb-2", "style": "width: 100%;"}),
    )
    categoria = forms.ChoiceField(
        label="Categoria",
        choices=Producto.Categoria.choices,
        widget=forms.Select(
            attrs={"class": "form-select mb-2", "style": "width: 100%;"}
        ),
    )
    imagen = forms.ImageField(
        label="Imagen",
        required=False,
        widget=forms.FileInput(
            attrs={"class": "btn btn-outline-dark mb-4", "style": "width: 100%;"}
        ),
    )

tt_app/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from .forms import RegistrationForm, CreacionDeProducto
from django.contrib.auth.forms import AuthenticationForm
from django.db import IntegrityError
from django.utils import timezone
from .models import CustomUser, Producto
from django.contrib.auth.decorators import login_required


# Create your views here.


def home(request):
    return render(request, "home.html")


def registro(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated:
        return HttpResponse(f"Ya estás registrado como {user.email}.")
    context = {}

    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get("email").lower()
            raw_password = form.cleaned_data.get("password1")
            first_name = form.cleaned_data.get("first_name")
            last_name = form.cleaned_data.get("last_name")
            dni = form.cleaned_data.get("dni")
            phone = form.cleaned_data.get("phone")
            birthdate = form.cleaned_data.get("birthdate")
            user = authenticate(
                email=email,
                password=raw_password,
                first_name=first_name,
                last_name=last_name,
                dni=dni,
                phone=phone,
                birthdate=birthdate,
            )
            destination = kwargs.get("next")
            if destination:
                return redirect(destination)
            return redirect("ingreso")
        else:
            context["registration_form"] = form

    return render(request, "registro.html", context)


def ingreso(request):
    if request.method == "GET":
        return render(request, "ingreso.html", {"form": AuthenticationForm})
    else:
        usuario = authenticate(
            request,
            email=request.POST["username"],
            password=request.POST["password"],
        )
        if usuario is None:
            return render(
                request,
                "ingreso.html",
                {"form": AuthenticationForm, "error": "Usuario o contraseña inválidos"},
            )
        else:
            login(request, usuario)
            return redirect("home")


def cerrar_sesion(request):
    logout(request)
    return redirect("home")


def crear_producto(request):
    if request.method == "POST":
        form = CreacionDeProducto(request.POST, request.FILES)
        if form.is_valid():
            producto = form.save(commit=False)
            producto.usuario = CustomUser.objects.get(id=2)
            # Establecer la fecha de publicación antes de guardar
            producto.fecha_de_publicacion = timezone.now()
            producto.save()
            # Redirigir a la página de productos
            return redirect("productos")
    else:
        form = CreacionDeProducto()
    return render(request, "products/crear_producto.html", {"form": form})


def productos(request):
    productos = Producto.objects.exclude(activo=False).order_by("-promocionado")
    return render(request, "products/productos.html", {"productos": productos})


def buscar_productos(request):
    if request.method == "GET":
        cadena = request.GET.get("cadena")
        productos_nom = Producto.objects.exclude(activo=False).filter(
            nombre__icontains=cadena
        )
        productos_desc = Producto.objects.exclude(activo=False).filter(
            descripcion__icontains=cadena
        )
        productos = productos_nom.union(productos_desc).order_by("-promocionado")
        return render(
            request,
            "products/buscar_productos.html",
            {"productos": productos, "cadena": cadena},
        )
    else:
        print("nao nao")
        return render(request, "products/productos.html", {"productos": productos})


def detalle_producto(request, id):
    producto = get_object_or_404(Producto, id=id)
    return render(request, "products/detalle.html", {"producto": producto})

tt_app/templates/products/buscar_productos.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if productos %}
<h3 class="ms-4 mt-3 mb-5 text-start">Resultados de su búsqueda "{{cadena}}": </h3>
    {% include 'products/partial_listado_productos.html' %}

{% else %}
    <h5 class="my-3 text-center">
        No hay productos que contengan "{{cadena}}" en su título o descripción.
    </h5> 
    <p class="text-center">
        <a href="{%url 'productos'%}">Volver a productos</a>
    </p>
{% endif %}

{%endblock%}

tt_app/templates/products/crear_producto.html
{% extends 'base.html' %}

{% block content %}


<main class="container my-5">
    <div class="row">
        <div class="col-md-4 offset-md-4" >
            <h2>Publicar producto</h2>
            <form method="POST" class="card card-body" enctype="multipart/form-data">
                {% csrf_token %}                
                {{form}}
                <button class="btn btn-primary">
                    <b>Aceptar</b>
                </button>
            </form>
        </div>
    </div>
</main>

{% endblock %}

tt_app/templates/products/detalle.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<div class="container p-4 mb-3">
{% if producto.activo %}
<div class="row">
    <div class="col-md-12">
        <div class="row">
            <div class="col-md-12">
                <h3 class=" mb-6">
                    {{producto.nombre}}
                </h3> 
                <div class=" my-4">
                <span class="badge badge-primary bg-primary">
                    <a href="#" class="text-decoration-none text-white">Categoria {{producto.get_categoria_display}}</a>    {# AGREGAR LINK A BUSQUEDA FILTRADA #}
                </span>
                {% if producto.promocionado %}
                <span class="badge badge-primary bg-warning">
                    <a href="#" class="text-decoration-none text-dark">Promocionado</a>    {# AGREGAR LINK A HU PROMOCIONAR UN PRODUCTO #}
                </span>
                {% else %}
                <span class="badge badge-secondary bg-secondary">
                    <a href="#" class="text-decoration-none text-white">No promocionado</a>    {# AGREGAR LINK A HU PROMOCIONAR UN PRODUCTO #}
                </span>
                {% endif %}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-5">
                {% if producto.imagen %}
                <img src="{{producto.imagen.url}}" alt="Imagen del producto" class="img-fluid border border-2" />
                {% else %}
                <img src="{%static 'images/default-image-missing.png'%}" alt="El producto no tiene imagenes" class="img-thumbnail" />
                {% endif %}
            </div>
            <div class="col-md-7">
                <p>
                    {{producto.descripcion}}
                </p>
                <p>
                    <small class="text-muted fw-light">
                    fecha de publicación: {{producto.fecha_de_publicacion|date:'l j, F Y'}}
                </small>
                </p>
            </div>
        </div>
    </div>
</div>
{% else %}
<h5 class=" p-6 text-center">
    Este producto ya no se encuentra disponible.
</h5> 
<p class=" p-2 text-center">
    <a href="{%url 'home'%}">Volver al inicio</a>
</p>
{% endif %}
</div>

{% endblock %}

tt_app/templates/products/partial_listado_productos.html
{% load static %}
<div class="row ">
    <div class="col-md-2 ">
        <div class="card card-body h-100 ">
        {%comment%}
        ESTE ES EL PANEL DE FILTROS POR CATEGORIA A IMPLEMENTAR
        <div class="d-grid gap-1 col-6 p-1 mx-auto">
            <button class="btn btn-secondary mb-2" type="button">0-5</button> 
            <button class="btn btn-secondary mb-2" type="button">5-10</button> 
            <button class="btn btn-secondary mb-2" type="button">10+</button> 
        </div>    
        {%endcomment%}
        </div>
    </div>
    <div class="col-md-10 ">

        {% for producto in productos %}
        {% if producto.activo %}
        <div class="card-group">    
            {% if producto.promocionado %}
            <div class="card card-body mb-2 border border-2 border-warning"  >
            {% else %}
            <div class="card card-body mb-2 " >
            {% endif %}
                <div class="row mh-100">
                    <div class="col-md-3 mh-100 d-flex justify-content-center align-items-center">
                        <div class="container h-100 " style="max-height: 30vh;">
                            {% if producto.imagen %}
                            <a href="{% url 'detalle_producto' producto.id%}"><img src="{{producto.imagen.url}}" alt="img"class="img-fluid mh-100 border border-2 rounded " /></a>
                            {% else %}
                            <img src="{% static 'images/default-image-missing.png' %}" alt="no img"  class="img-fluid border border-2 rounded"/>
                            {% endif %}
                        </div>
                        
                    </div>
                    <div class="col-md-9">
                        <div class="d-flex">
                            <div class="flex-grow-1 ">
                                <h4 class="card-title"><a href="{% url 'detalle_producto' producto.id%}" class=" text-decoration-none text-reset">{{producto.nombre}}</a></h4>
                            </div>
                            <div class="align-self-stretch">
                                {% if producto.promocionado %}
                                <span class="badge badge-primary bg-warning">
                                    <a href="#" class="text-decoration-none text-dark">Promocionado</a>    {# AGREGAR LINK A HU PROMOCIONAR UN PRODUCTO #}
                                </span>
                                {% else %}
                                {%comment%}
                                <span class="badge badge-secondary bg-secondary">
                                    <a href="#" class="text-decoration-none text-white">No promocionado</a>    {# AGREGAR LINK A HU PROMOCIONAR UN PRODUCTO #}
                                </span>
                                {%endcomment%}
                                {% endif %} 
                                <span class="badge badge-primary bg-primary">
                                    <a class="text-decoration-none text-white">Categoria {{producto.get_categoria_display}}</a>    
                                </span>
                            </div>
                        </div>
                        <p>{{producto.descripcion|striptags|truncatechars:190}}</p>
                        <small><p class="fw-light">{{producto.fecha_de_publicacion|date:'d M Y'|upper}}</p></small>
                        
                        <a href="" class="btn btn-primary">Solicitar intercambio</a>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
</div>

tt_app/templates/products/productos.html
{%extends 'base.html'%}

{% load static %}

{%block content%}

{% if productos %}
{#<a href="{% url 'home' %}" class="ms-4 mt-3 mb-5 text-start fw-light">Volver</a>  Link descartado #}
<h3 class="ms-4 mt-3 mb-5 text-start ">Se muestran todos los productos: </h3>
    {% include 'products/partial_listado_productos.html' %}

{% else %}
    <h5 class="my-3 text-center">
        No hay productos cargados aún.
    </h5> 
    <p class=" p-2 text-center">
        <a href="{%url 'home'%}">Volver al inicio</a>
    </p>
{% endif %}

{%endblock%}